import Head from 'next/head'
import { Inter } from '@next/font/google'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Login() {
  return (
    <>
      <Head>
      <title>Login Treli</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
        <div>
          <h1>Login</h1>
          <Link href='/'>Volver al Home</Link>
        </div>
    </>
  )
}
